version: '1'
services:
  mysql:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 2174
      MYSQL_DATABASE: protocol_db
    ports:
      - "3333:3306"
#    volumes:
#      - /var/lib/mysql/mysql.sock:/var/run/mysqld/mysqld.sock
  redis:
    image: 'bitnami/redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
#      - REDIS_PASSWORD=p123
#      - REDIS_PORT_NUMBER=7000
    ports:
      - "7000:6379"
#    volumes:
#      - /path/to/redis-persistence:/bitnami/redis/data

#  zookeeper:
#    image: wurstmeister/zookeeper
#    restart: unless-stopped
#    ports:
#      - "2222:2181"
#  kafka:
#    image: wurstmeister/kafka
#    restart: unless-stopped
#    ports:
#      - "9999:9092"
#    environment:
#      DOCKER_API_VERSION: 1.22
#      KAFKA_ADVERTISED_HOST_NAME: localhost
#      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2222
#    volumes:
#      - /var/run/docker.sock:/var/run/docker.sock