spring:
  profiles:
    active: dev
#  jpa:
#    properties:
#      hibernate:
#        enable_lazy_load_no_trans: true

server:
  port: 8081

# allowed origins
# example: http://localhost:3000,http://localhost:3001
cors:
  allowed:
    origins: http://localhost:8080