jwt:
  token:
    secret: imdenikandiwantmanymanymoney
    expiredTimeInMinutes: 30
    cookie:
      name: token
      path: /
      age: 512
# jwt vkontakte attribute
yandex:
  firstName: first_name
  lastName: last_name
  birthday: birthday
  email: default_email

# jwt vkontakte attribute
vkontakte:
  firstName: first_name
  lastName: last_name
  birthday: bdate
  email: email

# security oauth2 providers
spring:
  security:
    oauth2:
      client:
        registration:
          yandex:
            client-id: 173737bd6855472aa89b0c2222803eb3
            client-secret: d47aac3a30af4098b8452234e1125b99
            scope:
              - login:email
              - login:info
              - login:birthday
              - login:avatar
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/yandex
            client-authentication-method: POST
            client-name: yandex
            provider: yandex
            authorization-uri: https://oauth.yandex.ru/authorize
            token-uri: https://oauth.yandex.ru/token
            user-info-uri: https://login.yandex.ru/info?format=json&jwt_secret=d47aac3a30af4098b8452234e1125b99&with_openid_identity=1
            user-name-attribute: email
            user-info-authentication-method: FORM




