spring:
  autoconfigure:
    exclude:
      # disables the default creation of a account with a description in the password logs
      - org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration
# jwt
jwt:
  secret:
    access: qBTmv4oXFFR2GwjexDJ4t6fsIUIUhhXqlktXjXdkcyygs8nPVEwMfo29VDRRepYDVV5IkIxBMzr7OEHXEHd37w==
    refresh: zL1HB3Pch05Avfynovxrf/kpF9O2m4NCWKJUjEp27s9J2jEG3ifiKCGylaZ8fDeoONSTJP/wAzKawB8F9rOMNg==
  minutes:
    access: 30
  days:
    refresh: 30
