spring:
  datasource:
    url: jdbc:mysql://localhost:3390/protocol_db
    username: root
    password: 2174
  jpa:
    hibernate:
      #dialect: org.hibernate.dialect.MySQLDialect
      ddl-auto: create-drop
    show_sql: true
  cache:
    # disabled cache
    type: NONE
  # REDIS (RedisProperties)
  redis:
    database: 0
    host: localhost
    port: 6390
    password: p123
#mySettings
mySettings:
    redis:
      # cache 1 minute
      eventAnswerCache: 1

      #    timeout: 0
#    pool:
#      max-active: 8
#      max-wait: -1
#      max-idle: 8
#      min-idle: 0

