spring:
  datasource:
    url: jdbc:mysql://protocol-mysql:3390/protocol_db
    username: root
    password: 2174
  jpa:
    hibernate:
      #dialect: org.hibernate.dialect.MySQLDialect
      ddl-auto: create
    show_sql: false
# REDIS (RedisProperties)
  redis:
    database: 0
    host: protocol-redis
    port: 6390
    password: p123
mySettings:
  redis:
    eventAnswerCache: 30
#    timeout: 0
#    pool:
#      max-active: 8
#      max-wait: -1
#      max-idle: 8
#      min-idle: 0